version: '3.8'

services:
  postgres:
    platform: linux/amd64
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=mokopass
      - POSTGRES_DB=go_native
    ports:
      - 5432:5432
  services:
    build: 
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./config.env
    ports:
      - 8080:8080
    environment:
      - DB_SOURCE=postgresql://root:mokopass@postgres/go_native?sslmode=disable
    depends_on:
      - postgres
    # entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", ]
    # volumes:
    #   - .:/app
    # command: go run cmd/main.go -b 0.0.0.0
  
