// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package account

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	DeleteAccount(ctx context.Context, id uuid.UUID) (Account, error)
	GetDetailAccount(ctx context.Context, id uuid.UUID) (GetDetailAccountRow, error)
	GetListAccount(ctx context.Context, arg GetListAccountParams) ([]GetListAccountRow, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
}

var _ Querier = (*Queries)(nil)
